manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      # dec 14th: https://github.com/zmkfirmware/zmk/commit/930b5cc058698986fabc1be96427c14937e983ea
      #revision: 930b5cc058698986fabc1be96427c14937e983ea
      # revision: 5138c6fb14783b756c5a3e61581625c700f3555b
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
  self:
    path: config
